### ISSUE TITLE
Create sidebar component - Vue

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/tbd-examples#75]
# Create sidebar component - Vue

## 🚀 Goal
Create a sidebar component in Vue that provides navigation and Web5 connection functionality for our Decentralized Web App (DWA) starter.

## 🤔 Background
Our DWA needs a sidebar for navigation and displaying the Web5 connection status. We need to implement this in Vue, matching the functionality of the existing React implementation in our DWA starter app.

> This is part of our larger project to create a Vue.js DWA starter. See our [main issue here](https://github.com/TBD54566975/tbd-examples/issues/63) for the full context and list of all related tasks.

> **Important:** For reference, please see the [DWA React Vite starter app](https://github.com/TBD54566975/tbd-examples/tree/main/javascript/dwa-starter-react-vite). While the implementation details will differ for Vue, this example provides a good overview of the structure and functionalities of a DWA.

## 🔑 Tasks and Acceptance Criteria
- [ ] Create a `Sidebar.vue` component
- [ ] Implement a toggleable sidebar that can be opened and closed
- [ ] Create navigation menu items for Home, Settings (when connected), and About
- [ ] Integrate with the existing Vue Router setup for navigation between pages
- [ ] Implement Web5 connection functionality:
  - [ ] Add a "Connect" button when the user is not connected
  - [ ] When connected, display "Hi, did:1234..." where 1234 are the first few characters of the user's DID
  - [ ] The Settings menu item should only be visible when the user is connected
- [ ] Make the sidebar responsive for mobile devices
- [ ] Style the component using Tailwind CSS to match the existing design

## 🌟 Resources
- [Web5 documentation](https://developer.tbd.website/docs/web5/decentralized-web-nodes/web5-connect)
- [Vue.js Documentation](https://vuejs.org/guide/introduction.html)
- [Vue Router Documentation](https://router.vuejs.org/)
- [Tailwind CSS Documentation](https://tailwindcss.com/docs)
- [Lucide Vue Icons](https://lucide.dev/guide/packages/lucide-vue-next)
- [DWA React Vite Starter App](https://github.com/TBD54566975/tbd-examples/tree/main/javascript/dwa-starter-react-vite) (for reference)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://github.com/TBD54566975/tbd-examples/issues/64#) community.

Happy coding! 🎉

**Comment by Johnnyevans32** [comment]
hi @blackgirlbytes this has been sorted in one of previous pr, how can it be closed

**Comment by blackgirlbytes** [comment]
Hmm I thought mentioning it in a previous PR would close it but I guess i just have to manually close this one. Thanks!

**Comment by Johnnyevans32** [comment]
hi @blackgirlbytes, seems cos a point weight label wasn't added to this issue, I didn't receive points for it

**Comment by blackgirlbytes** [comment]
@Johnnyevans32 the points are coming from the labels on every pull request..not every issue. There's a github action i made that looks for if the PR is merged and has a size label. To ensure you get the right points, maybe if possible..make sure sure you do separate PRs for each task.

I'll try to figure out how you can get points for the sidebar component. I might have to make a new size label or wait until the very end of the month to update your points manually

**Comment by Johnnyevans32** [comment]
> @Johnnyevans32 the points are coming from the labels on every pull request..not every issue. There's a github action i made that looks for if the PR is merged and has a size label. To ensure you get the right points, maybe if possible..make sure sure you do separate PRs for each task.
> 
> I'll try to figure out how you can get points for the sidebar component. I might have to make a new size label or wait until the very end of the month to update your points manually because if i write it in manually..the action will just write over it when it runs again

yeah I totally understand, thank you ❤️

**Comment by Johnnyevans32** [comment]
hi @blackgirlbytes, gentle reminder on this
