### ISSUE TITLE
Create basic "Hello World" Vanilla.js app

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/tbd-examples#82]
## 🚀  Goal
Set up a basic Vanilla.js project structure and create a simple application that renders the words "Hello World" on the screen. This will serve as the foundation for our Decentralized Web App (DWA) starter in Vanilla.

## 🤔 Background
We're expanding our DWA starter collection to include Vanilla.js. This task is the first step in creating a Vanilla.js version of our DWA starter app, which will help developers kickstart their Web5 projects using Vanilla.

> This is part of our larger project to create a Vanilla.js DWA starter. See our [main issue here](https://github.com/TBD54566975/tbd-examples/issues/81) for the full context and list of all related tasks.

## 🔑  Tasks and Acceptance Criteria

- [ ] Set up a new Vanilla.js project using Vanilla CLI or Vite
- [ ] Create a basic project structure following Vanilla.js best practices
- [ ] Ensure landing page renders the words "Hello, World!"
- [ ] Ensure the app runs without errors

## 🌟 Resources

- [Vanilla JS Documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Introduction)
- [Web5 Documentation](https://developer.tbd.website/docs/web5/decentralized-web-nodes/access-data-with-drls)
- [Progressive Web Apps](https://web.dev/explore/progressive-web-apps)

## Getting Started

1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.
Happy coding! 🎉

**Comment by Adjoa** [comment]
.take

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me @blackgirlbytes

**Comment by 29deepanshutyagi** [comment]
.take
